In [10]:
#1.	Write a Python Program to Add Two Matrices?
import numpy as np
def takeInputMatrix(n1,n2):
    arr=[]
    for i in range(n1):
        col = []
        for j in range(n2):
            col.append(int(input()))
        arr.append(col)
    return tuple(arr)

n1=int(input('Enter number of rows:'))
n2=int(int(input('Enter number of columns:')))
print('Enter first matrix elements:')
arr1=np.array(tuple(takeInputMatrix(n1,n2)))
print('Enter second matrix elements:')
arr2=np.array(tuple(takeInputMatrix(n1,n2)))
sum_arr=arr1+arr2
print('Addition of two matrices :\n',sum_arr)



Enter number of rows:2
Enter number of columns:2
Enter first matrix elements:
1
2
3
4
Enter second matrix elements:
1
1
1
1
Addition of two matrices :
 [[2 3]
 [4 5]]


In [16]:
#2.	Write a Python Program to Multiply Two Matrices?
import numpy as np
def takeInputMatrix(n1,n2):
    arr=[]
    for i in range(n1):
        col = []
        for j in range(n2):
            col.append(int(input()))
        arr.append(col)
    return tuple(arr)

n1=int(input('Enter number of rows:'))
n2=int(int(input('Enter number of columns:')))
print('Enter first matrix elements:')
arr1=np.array(tuple(takeInputMatrix(n1,n2)))
print('Enter second matrix elements:')
arr2=np.array(tuple(takeInputMatrix(n1,n2)))
mul=np.matmul(arr1,arr2)
mul

Enter number of rows:2
Enter number of columns:2
Enter first matrix elements:
1
1
1
1
Enter second matrix elements:
1
1
1
1


array([[2, 2],
       [2, 2]])

In [18]:
#3.	Write a Python Program to Transpose a Matrix?
import numpy as np
def takeInputMatrix(n1,n2):
    arr=[]
    for i in range(n1):
        col = []
        for j in range(n2):
            col.append(int(input()))
        arr.append(col)
    return tuple(arr)

n1=int(input('Enter number of rows:'))
n2=int(int(input('Enter number of columns:')))
print('Enter  matrix elements:')
arr1=np.array(tuple(takeInputMatrix(n1,n2)))
print('Transpose of the matrix:\n',arr1.T)

Enter number of rows:2
Enter number of columns:2
Enter  matrix elements:
1
2
3
4
Transpose of the matrix:
 [[1 3]
 [2 4]]


In [19]:
#4.	Write a Python Program to Sort Words in Alphabetic Order?
my_str = input("Enter a string: ")
words = [word.lower() for word in my_str.split()]
words.sort()
print("The sorted words are:")
for word in words:
    print(word)


Enter a string: Harsha is good man with kidney
The sorted words are:
good
harsha
is
kidney
man
with


In [23]:
#5.	Write a Python Program to Remove Punctuation From a String?
my_str = input("Enter a string: ")
res=''
for i in my_str:
    if(i.isalnum() or i==' '):
        res+=i
    else:
        continue
res

Enter a string: !!Harsha is datascientist, nade by his passion.


'Harsha is datascientist nade by his passion'